# Generated by Django 3.2 on 2022-05-08 03:42

from django.db import migrations, models
import sample.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandwritingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sample.models.handwriting_img_path)),
            ],
        ),
    ]
